# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_movies_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'

  # Pods for rn_movies_app
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', :path => rn_path

  target 'rn_movies_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'rn_movies_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
